### PR TITLE
refactor(presets): adjust tabs preset to support mobile viewport

### PR DESCRIPTION
**Pull request by sozonome**
### Description

Currently the tabs is not mobile optimized yet (resulting in overflowed width)

### Proposed Solution

Update tabs recipes to support mobile viewport
References: shadcn/ui's tabs

### Previews

| Before | After |
|---|---|
| <video src="https://github.com/cschroeter/park-ui/assets/17046154/80f91ba1-9a69-4eba-93ce-f310b54ba745" />  | <video src="https://github.com/cschroeter/park-ui/assets/17046154/f2d8670c-3056-40bf-aba3-1c71b7e93786" /> |

### CODE REVIEW

**Comment by cschroeter** [comment]
Thanks for taking your time to create this PR. Much appreciated.
I noticed that the indicator is somewhat hidden now:

image


https://github.com/cschroeter/park-ui/assets/1846056/a6ee49df-c0b4-418a-bb42-9b214011cc48

Could you double check? If you run out of time I will check this later. Again thanks gain <3

**Comment by sozonome** [comment]
> Thanks for taking your time to create this PR. Much appreciated. I noticed that the indicator is somewhat hidden now:
> 
> image
>  1px.mov 
> Could you double check? If you run out of time I will check this later. Again thanks gain <3

Sure @cschroeter , I'll be happy to check onto it, will update

**Comment by sozonome** [comment]
After trying, I think I might need help as I'm starting to wonder if this should be fixed through Ark UI

The culprit is adding overflow scroll makes the indicator hidden, while before setting it, it can overlap with the container border.

@cschroeter

**Comment by cschroeter** [comment]
image
you have to run this pr locally.  haha

**Comment by sozonome** [comment]
Right...TIL we can replace bottom border with box shadow 🙏

**Pull request merged**
