### PR TITLE
chore(tooltip): remove useless exports

### PR DESCRIPTION
**Pull request by kovsu**

### CODE REVIEW

**Comment by cschroeter** [comment]
@kovsu 

I've fixed this in the Ark 2.0 PR. The auto generated snippets look now you like this:


```jsx
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import type { ComponentProps } from 'react'
import { styled } from 'styled-system/jsx'
import { tooltip } from 'styled-system/recipes'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(tooltip)

export const TooltipRoot = withProvider(ArkTooltip.Root)
export const TooltipArrow = withContext(styled(ArkTooltip.Arrow), 'arrow')
export const TooltipArrowTip = withContext(styled(ArkTooltip.ArrowTip), 'arrowTip')
export const TooltipContent = withContext(styled(ArkTooltip.Content), 'content')
export const TooltipPositioner = withContext(styled(ArkTooltip.Positioner), 'positioner')
export const TooltipTrigger = withContext(styled(ArkTooltip.Trigger), 'trigger')

export const Tooltip = {
  Root: TooltipRoot,
  Arrow: TooltipArrow,
  ArrowTip: TooltipArrowTip,
  Content: TooltipContent,
  Positioner: TooltipPositioner,
  Trigger: TooltipTrigger,
}

export interface TooltipRootProps extends ComponentProps<typeof TooltipRoot> {}
export interface TooltipArrowProps extends ComponentProps<typeof TooltipArrow> {}
export interface TooltipArrowTipProps extends ComponentProps<typeof TooltipArrowTip> {}
export interface TooltipContentProps extends ComponentProps<typeof TooltipContent> {}
export interface TooltipPositionerProps extends ComponentProps<typeof TooltipPositioner> {}
export interface TooltipTriggerProps extends ComponentProps<typeof TooltipTrigger> {}

```


Any suggestions?

**Comment by cschroeter** [comment]
@kovsu 

Sou you would skip full imports like `import { TooltipArrow } from ' ~/components/ui/tooltip'` ?

**Comment by cschroeter** [comment]
@kovsu 

With nextjs this is the only setup I could get to work:

```ts
'use client'
import { ark } from '@ark-ui/react/factory'
import { styled } from 'styled-system/jsx'
import { card } from 'styled-system/recipes'
import { createStyleContext } from '~/lib/create-style-context'

const { withProvider, withContext } = createStyleContext(card)

const Root = withProvider(styled(ark.div), 'root')
const Body = withContext(styled(ark.div), 'body')
const Description = withContext(styled(ark.p), 'description')
const Footer = withContext(styled(ark.div), 'footer')
const Header = withContext(styled(ark.div), 'header')
const Title = withContext(styled(ark.h3), 'title')

export { Body, Description, Footer, Header, Root, Title }
```

**Comment by kovsu** [comment]
> @kovsu
> 
> Sou you would skip full imports like `import { TooltipArrow } from ' ~/components/ui/tooltip'` ?

oh, I forget this. 😂

**Pull request closed without merging**
