### PR TITLE
feat(checkbox): revise checkbox component api

### PR DESCRIPTION
**Pull request by kovsu**
I found that the `colorPlatte` attribute does not exist in the `ArkSwitch`, so if I add the prop to the tag, it will cause some type error. I think I need to spend some time to slove it. 🥲

### CODE REVIEW

**Comment by cschroeter** [comment]
> I found that the `colorPlatte` attribute does not exist in the `ArkSwitch`, so if I add the prop to the tag, it will cause some type error. I think I need to spend some time to slove it. 🥲

I can have a look later :)

**Comment by cschroeter** [comment]
@kovsu 
Thanks mate <3

**Comment by cschroeter** [comment]
@kovsu 

For now I use a work around but I guess there is a better way

```tsx
export interface CheckboxProps
  extends ArkCheckboxProps,
    CheckboxVariantProps,
    Omit<HTMLStyledProps<'label'>, 'defaultChecked' | 'dir' | 'translate' | 'content' | 'color'> {
  children?: ReactNode
}
```

**Comment by kovsu** [comment]
I didn't know the HTMLStyledProps, but now I got it.😀

**Pull request merged**
